name: Import Repo Rulesets

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup GitHub CLI
        run: |
          echo "Setting up GitHub CLI"
          gh --version

      - name: Run script
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: | 
            bash ./scripts/import-rulesets.sh newfold-labs